### ISSUE TITLE
autorecon after pipx install with "module 'importlib' has no attribute 'util'"

### ISSUE THREAD

**Issue by devnull15** [Tib3rius/AutoRecon#156]
pipx install of autorecon fails to run:

```
└─$ autorecon 
Traceback (most recent call last):
  File "/home/kali/.local/bin/autorecon", line 8, in <module>
    sys.exit(main())
  File "/home/kali/.local/pipx/venvs/autorecon/lib/python3.9/site-packages/autorecon/main.py", line 1539, in main
    asyncio.run(run())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/kali/.local/pipx/venvs/autorecon/lib/python3.9/site-packages/autorecon/main.py", line 921, in run
    spec = importlib.util.spec_from_file_location("autorecon." + filename[:-3], os.path.join(dirname, filename))
AttributeError: module 'importlib' has no attribute 'util'

```

OS is latest version of kali 2022.1 downloaded same day as issue submission.

**Comment by Tib3rius** [comment]
Can you try the latest and let me know if that fixes it?

**Comment by mechahop** [comment]
Have the same issue, but editing the import in main.py to importlib.util makes it work.

**Comment by mechahop** [comment]
Oops @Tib3rius just realized you pushed a update, I updated and works fine now too! :)

**Comment by devnull15** [comment]
works! Thanks @Tib3rius
