### ISSUE TITLE
Pipx Install Method - JSON Broken

### ISSUE THREAD

**Issue by BaddK** [Tib3rius/AutoRecon#177]
Attempt to install using the pipx method and it breaks at the this part:

```
pipx install git+https://github.com/Tib3rius/AutoRecon.git                                                                           1 ⨯
Traceback (most recent call last):
  File "/home/baddk/.local/bin/pipx", line 8, in <module>
    sys.exit(cli())
  File "/home/baddk/.local/lib/python3.10/site-packages/pipx/main.py", line 819, in cli
    return run_pipx_command(parsed_pipx_args)
  File "/home/baddk/.local/lib/python3.10/site-packages/pipx/main.py", line 202, in run_pipx_command
    return commands.install(
  File "/home/baddk/.local/lib/python3.10/site-packages/pipx/commands/install.py", line 30, in install
    package_name = package_name_from_spec(
  File "/home/baddk/.local/lib/python3.10/site-packages/pipx/commands/common.py", line 333, in package_name_from_spec
    package_name = venv.install_package_no_deps(
  File "/home/baddk/.local/lib/python3.10/site-packages/pipx/venv.py", line 268, in install_package_no_deps
    old_package_set = self.list_installed_packages()
  File "/home/baddk/.local/lib/python3.10/site-packages/pipx/venv.py", line 348, in list_installed_packages
    pip_list = json.loads(cmd_run.stdout.strip())
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
On the latest version of kali rolling.

**Comment by Tib3rius** [comment]
@BaddK none of those error messages seem to relate to AutoRecon. I would suggest making sure that your Python and pipx are installed properly and up to date.
