### ISSUE TITLE
ModuleNotFoundError: No module named 'autorecon'

### ISSUE THREAD

**Issue by pafranci** [Tib3rius/AutoRecon#203]
┌──(kali㉿kali)-[~/home]
└─$ autorecon             
Traceback (most recent call last):
  File "/usr/local/bin/autorecon", line 5, in <module>
    from autorecon.main import main
ModuleNotFoundError: No module named 'autorecon'

**Comment by Tib3rius** [comment]
Hi @pafranci, which method did you use to install AutoRecon?

**Comment by pafranci** [comment]
hi Tib3rius, it's been a long time since I installed it but I believe I
used the first method, pipx. It was working fine for months until I got
that error message. Must have been due to a failed apt get update I
recently had. I am now using the script installed using method #2 and it's
been working fine.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by kaliankhe** [comment]
having same issue 
─root at Optimus in /home/kali/CTF/pgpractis/PlanetExpress
╰─○ autorecon --only-scans-dir -v 192.168.189.205
Traceback (most recent call last):
  File "/usr/local/bin/autorecon", line 5, in <module>
    from autorecon.main import main
ModuleNotFoundError: No module named 'autorecon'
╭─root at Optimus in /home/kali/CTF/pgpractis/PlanetExpress
╰─○ autorecon                                    
Traceback (most recent call last):
  File "/usr/local/bin/autorecon", line 5, in <module>
    from autorecon.main import main
ModuleNotFoundError: No module named 'autorecon'

**Comment by kaliankhe** [comment]
any update on this
