### ISSUE TITLE
Permission Error: [Errno 13] Permission denied 'opt/AutoRecon/src/autorecon/results

### ISSUE THREAD

**Issue by CybertSys** [Tib3rius/AutoRecon#52]
I'm getting this error when trying to execute the command:

Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "autorecon.py", line 644, in scan_host
    os.makedirs(basedir, exist_ok=True)
  File "/usr/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/opt/AutoRecon/src/autorecon/results'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "autorecon.py", line 880, in <module>
    main()
  File "autorecon.py", line 868, in main
    future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
PermissionError: [Errno 13] Permission denied: '/opt/AutoRecon/src/autorecon/results'

**Comment by samuel-emrys** [comment]
Further information required. Can you tell us:
- How you installed AutoRecon
- How you executed AutoRecon
    - The command you used
    - The directory you were in
- The permissions of `/opt/AutoRecon`

**Comment by CybertSys** [comment]
Samuel. I figured it out. I was not running the command from the correct
directory.

Thank you.
