### ISSUE TITLE
TypeErrors 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by oxidizeddreams** [Tib3rius/AutoRecon#54]
`[*] Scanning target 127.0.0.1
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/sysko/PycharmProjects/osint/AutoRecon/src/autorecon/autorecon.py", line 679, in scan_host
    loop.run_until_complete(scan_services(loop, semaphore, target))
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/sysko/PycharmProjects/osint/AutoRecon/src/autorecon/autorecon.py", line 485, in scan_services
    for profile in port_scan_profiles_config:
TypeError: 'NoneType' object is not iterable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/autorecon/autorecon.py", line 880, in <module>
    main()
  File "src/autorecon/autorecon.py", line 868, in main
    future.result()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
TypeError: 'NoneType' object is not iterable`

**Comment by samuel-emrys** [comment]
What command did you execute? Can you provide steps to reproduce it? What method did you use for installation?

**Comment by Metaspl01t-006** [comment]
Same problem here

**Comment by Metaspl01t-006** [comment]
Installed with pipx
and command was
autorecon 127.0.0.1

**Comment by Metaspl01t-006** [comment]
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/process.py", line 243, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/ac/.local/pipx/venvs/autorecon/lib/python3.9/site-packages/autorecon/autorecon.py", line 679, in scan_host
    loop.run_until_complete(scan_services(loop, semaphore, target))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/ac/.local/pipx/venvs/autorecon/lib/python3.9/site-packages/autorecon/autorecon.py", line 485, in scan_services
    for profile in port_scan_profiles_config:
TypeError: 'NoneType' object is not iterable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ac/.local/bin/autorecon", line 8, in <module>
    sys.exit(main())
  File "/Users/ac/.local/pipx/venvs/autorecon/lib/python3.9/site-packages/autorecon/autorecon.py", line 868, in main
    future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
TypeError: 'NoneType' object is not iterable

**Comment by samuel-emrys** [comment]
@Metaspl01t-006 does the file `~/.config/AutoRecon/port_scan_profiles.toml` exist?

**Comment by Spl01ter** [comment]
Nope

**Comment by Spl01ter** [comment]
Found the problem.
~/.config/AutoRecon/port_scan_profiles.toml is named ~/.config/AutoRecon/port_scan_profiles_default.toml

**Comment by Spl01ter** [comment]
Problem still exists even when the files are renamed

**Comment by Spl01ter** [comment]
I think it is a problem with python@3.9 rather than AutoRecon

**Comment by Spl01ter** [comment]
Works perfectly fine on Kali Linux with python@3.7

**Comment by jonnyhoff** [comment]
> Installed with pipx
> and command was
> autorecon 127.0.0.1

Same issue.

**Comment by jonnyhoff** [comment]
MacOS + Python 3.9.0
