### ISSUE TITLE
ValueError: Separator is found, but chunk is longer than limit

### ISSUE THREAD

**Issue by juhulian** [Tib3rius/AutoRecon#68]
Hi,

I am using the current version from git, Python 3.9.1rc1 on a Kali 2020.4, and get between the output of AutoRecon several times the following error:

```
Task exception was never retrieved
future: <Task finished name='Task-347' coro=<read_stream() done, defined at /home/kali/git/AutoRecon/src/autorecon/autorecon.py:221> exception=ValueError('Separator is not found, and chunk exceed the limit')>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/streams.py", line 540, in readline
    line = await self.readuntil(sep)
  File "/usr/lib/python3.9/asyncio/streams.py", line 618, in readuntil
    raise exceptions.LimitOverrunError(
asyncio.exceptions.LimitOverrunError: Separator is not found, and chunk exceed the limit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/git/AutoRecon/src/autorecon/autorecon.py", line 224, in read_stream
    line = await stream.readline()
  File "/usr/lib/python3.9/asyncio/streams.py", line 549, in readline
    raise ValueError(e.args[0])
ValueError: Separator is not found, and chunk exceed the limit
```

I'm not sure what this is or what impact it has. Maybe this is a problem with Python 3.9?
Many thanks and greetings

**Comment by sgt4779** [comment]
I have them same issue. I have another VM with Auto recon on it and it does not do that. I figure the New Kali is missing something as my older version of kali works with it fine.  Hope there is a fix for this.

**Comment by Coen-Schuijt** [comment]
There seems to be an issue with an out of bound on the limit parameter (see: https://stackoverflow.com/questions/55457370/how-to-avoid-valueerror-separator-is-not-found-and-chunk-exceed-the-limit).

Change line 277 of the file /home/kali/.local/pipx/venvs/autorecon/lib/python3.9/site-packages/autorecon/autorecon.py
```python
# Old
#process = await asyncio.create_subprocess_shell(cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE, executable='/bin/bash')
# Increase limit to stop fuff from failing
process = await asyncio.create_subprocess_shell(cmd, stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE, limit=1024 * 128, executable='/bin/bash')
```
