### ISSUE TITLE
ModuleNotFoundError: No module named 'autorecon'

### ISSUE THREAD

**Issue by L0uisJ0shua** [Tib3rius/AutoRecon#71]
Hi Tib3rius,

Was hoping I could get your help on this. I think there is an update on the stuff that Autorecon is built on as my autorecon has stopped working all of a sudden after my most recent update on my Kali Linux Machine. I ran my usual command sudo env "PATH=$PATH" autorecon <ip address> and it returned and error

```
Traceback (most recent call last):
  File "/home/kali/.local/bin/autorecon", line 5, in <module>
    from autorecon.autorecon import main
ModuleNotFoundError: No module named 'autorecon'
```

I also tried to reinstall autorecon in which I ran `pipx install git+https://github.com/Tib3rius/AutoRecon.git` which resulted in the following error:

```
Traceback (most recent call last):
  File "/home/kali/.local/bin/pipx", line 8, in <module>
    sys.exit(cli())
  File "/home/kali/.local/lib/python3.9/site-packages/pipx/main.py", line 609, in cli
    return run_pipx_command(parsed_pipx_args)
  File "/home/kali/.local/lib/python3.9/site-packages/pipx/main.py", line 156, in run_pipx_command
    return commands.install(
  File "/home/kali/.local/lib/python3.9/site-packages/pipx/commands/install.py", line 27, in install
    package_name = package_name_from_spec(
  File "/home/kali/.local/lib/python3.9/site-packages/pipx/commands/common.py", line 257, in package_name_from_spec
    package_name = venv.install_package_no_deps(
  File "/home/kali/.local/lib/python3.9/site-packages/pipx/venv.py", line 233, in install_package_no_deps
    old_package_set = self.list_installed_packages()
  File "/home/kali/.local/lib/python3.9/site-packages/pipx/venv.py", line 333, in list_installed_packages
    pip_list = json.loads(cmd_run.stdout.strip())
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

Let me know if you need more details

**Comment by L0uisJ0shua** [comment]
My guess is that it might have been a python update. Since the error is found in the python3 decoder?

**Comment by jtlobdell** [comment]
I just resolved this issue (or a similar one) on my own Kali VM.

In my case, I had installed autorecon using pip3 on python3.8. Upgrading to python3.9 left packages for 3.8 in the python3.8 directory where the newer version doesn't look.

You can check for a similar situation by checking the python version:
```
$ python3 --version
Python 3.9.1
```
and looking for autorecon in old python directories, e.g.
`$ ls /usr/local/lib/python3.8/dist-packages`

To fix this I installed python3.8
`$ sudo apt install python3.8`
then uninstalled autorecon from that version
`$ sudo python3.8 -m pip uninstall autorecon`

I then installed using the pipx instructions (see README) which should hopefully prevent this in the future.

**Comment by L0uisJ0shua** [comment]
@jtlobdell oh wow thanks! so the break is due to the usage of pip3 installing autorecon? I ended up reverting to a previous snapshot to use it.
